[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MagnetoTransport = "69a1719d-56a7-4bd5-a19b-0cc479363a4d"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Piecewise = "f03ddd90-437e-4cf2-8f6c-e62f92609b90"
PiecewiseHilbert = "fb75a84c-a7ae-4011-94d8-abc4bb6dbff9"
PiecewiseLorentz = "5265c256-a0b7-4541-80b8-9bb011dcc609"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
MagnetoTransport = {path = "../"}
Piecewise = {subdir = "Piecewise", url = "https://github.com/ChristopheBerthod/Piecewise.jl"}
PiecewiseHilbert = {subdir = "PiecewiseHilbert", url = "https://github.com/ChristopheBerthod/Piecewise.jl"}
PiecewiseLorentz = {subdir = "PiecewiseLorentz", url = "https://github.com/ChristopheBerthod/Piecewise.jl"}

[compat]
Documenter = "1.8"
